// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlite

import (
	"database/sql"
)

type FileMetum struct {
	ID          string         `json:"id"`
	ParentID    sql.NullString `json:"parent_id"`
	ThumbID     sql.NullString `json:"thumb_id"`
	Name        string         `json:"name"`
	ContentType string         `json:"content_type"`
	Size        int64          `json:"size"`
	UploadDate  string         `json:"upload_date"`
	Owner       string         `json:"owner"`
}

type User struct {
	ID         string         `json:"id"`
	Email      string         `json:"email"`
	Token      sql.NullString `json:"token"`
	BucketName string         `json:"bucket_name"`
}
