// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlite

import (
	"database/sql"

	"github.com/google/uuid"
)

type File struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Owner       string         `json:"owner"`
	ContentType string         `json:"content_type"`
	FilePath    string         `json:"file_path"`
	ThumbPath   sql.NullString `json:"thumb_path"`
}
