// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlite

import (
	"database/sql"
)

type File struct {
	ID          string         `json:"id"`
	ParentID    sql.NullString `json:"parent_id"`
	Name        string         `json:"name"`
	ContentType string         `json:"content_type"`
	Owner       string         `json:"owner"`
}
