// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	CreateFileMeta(ctx context.Context, arg CreateFileMetaParams) error
	DeleteFileMeta(ctx context.Context, arg DeleteFileMetaParams) error
	GetAllFileMeta(ctx context.Context) ([]FileMetum, error)
	GetFileMeta(ctx context.Context, id string) (FileMetum, error)
	GetFileMetaByNameAndOwner(ctx context.Context, name string) (FileMetum, error)
	GetUser(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
