// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

type Metadata struct {
	ID        string `json:"id"`
	FileName  string `json:"file_name"`
	ThumbName string `json:"thumb_name"`
	UserID    string `json:"user_id"`
}

type User struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	BucketName string `json:"bucket_name"`
}
