// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type Metadata struct {
	ID        string         `json:"id"`
	FileName  string         `json:"file_name"`
	ThumbName sql.NullString `json:"thumb_name"`
	UserID    string         `json:"user_id"`
	DeletedAt sql.NullString `json:"deleted_at"`
}

type User struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	BucketName string `json:"bucket_name"`
}
