// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlite

import (
	"context"
)

const deleteMetadata = `-- name: DeleteMetadata :exec
DELETE FROM metadata 
WHERE id = ?
AND user_id = ?
`

type DeleteMetadataParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMetadata(ctx context.Context, arg DeleteMetadataParams) error {
	_, err := q.exec(ctx, q.deleteMetadataStmt, deleteMetadata, arg.ID, arg.UserID)
	return err
}

const getAllMetadata = `-- name: GetAllMetadata :many
SELECT id, file_name, thumb_name, user_id FROM metadata 
WHERE user_id = ?
`

func (q *Queries) GetAllMetadata(ctx context.Context, userID string) ([]Metadata, error) {
	rows, err := q.query(ctx, q.getAllMetadataStmt, getAllMetadata, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metadata
	for rows.Next() {
		var i Metadata
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.ThumbName,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadata = `-- name: GetMetadata :one
SELECT id, file_name, thumb_name, user_id FROM metadata 
WHERE id = ? 
AND user_id = ? LIMIT 1
`

type GetMetadataParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMetadata(ctx context.Context, arg GetMetadataParams) (Metadata, error) {
	row := q.queryRow(ctx, q.getMetadataStmt, getMetadata, arg.ID, arg.UserID)
	var i Metadata
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.ThumbName,
		&i.UserID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, bucket_name FROM users 
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.BucketName)
	return i, err
}

const saveMetadata = `-- name: SaveMetadata :exec
INSERT INTO metadata (
	id, file_name, thumb_name, user_id
) VALUES (
	?, ?, ?, ?
)
`

type SaveMetadataParams struct {
	ID        string `json:"id"`
	FileName  string `json:"file_name"`
	ThumbName string `json:"thumb_name"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SaveMetadata(ctx context.Context, arg SaveMetadataParams) error {
	_, err := q.exec(ctx, q.saveMetadataStmt, saveMetadata,
		arg.ID,
		arg.FileName,
		arg.ThumbName,
		arg.UserID,
	)
	return err
}
