// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	DeleteMetadata(ctx context.Context, arg DeleteMetadataParams) error
	GetMetadata(ctx context.Context, arg GetMetadataParams) (Metadata, error)
	GetUser(ctx context.Context, email string) (User, error)
	SaveMetadata(ctx context.Context, arg SaveMetadataParams) error
	UpdateMetadata(ctx context.Context, arg UpdateMetadataParams) error
}

var _ Querier = (*Queries)(nil)
