CREATE TABLE IF NOT EXISTS users (
		id TEXT NOT NULL PRIMARY KEY,
		email TEXT NOT NULL UNIQUE,
		bucket TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS metadata (
		id TEXT NOT NULL PRIMARY KEY, 
		file_name TEXT NOT NULL, 
		thumb_name TEXT NOT NULL,
		user_id TEXT NOT NULL,
		UNIQUE (file_name, user_id)
);
